/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/admin/layouts/AdminLayout.vue')['default']
    BadgeButton: typeof import('./src/components/frontend/BadgeButton.vue')['default']
    CardSkeleton: typeof import('./src/components/admin/common/CardSkeleton.vue')['default']
    Footer: typeof import('./src/components/frontend/Footer.vue')['default']
    FormSkeleton: typeof import('./src/components/admin/common/FormSkeleton.vue')['default']
    GoogleMapEmbed: typeof import('./src/components/frontend/GoogleMapEmbed.vue')['default']
    Header: typeof import('./src/components/frontend/Header.vue')['default']
    Hero: typeof import('./src/components/frontend/Hero.vue')['default']
    ImageGalleryModal: typeof import('./src/components/frontend/ImageGalleryModal.vue')['default']
    ImagePlaceholder: typeof import('./src/components/common/ImagePlaceholder.vue')['default']
    ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
    Kontak: typeof import('./src/components/frontend/Kontak.vue')['default']
    Navbar: typeof import('./src/components/admin/Navbar.vue')['default']
    OurClient: typeof import('./src/components/frontend/OurClient.vue')['default']
    Pagination: typeof import('./src/components/frontend/Pagination.vue')['default']
    Produk: typeof import('./src/components/frontend/Produk.vue')['default']
    Riwayat: typeof import('./src/components/frontend/Riwayat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/frontend/SectionTitle.vue')['default']
    Sidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
    SkeletonLoader: typeof import('./src/components/admin/common/SkeletonLoader.vue')['default']
    StatsSkeleton: typeof import('./src/components/admin/common/StatsSkeleton.vue')['default']
    TableSkeleton: typeof import('./src/components/admin/common/TableSkeleton.vue')['default']
    Testimoni: typeof import('./src/components/frontend/Testimoni.vue')['default']
    ToastNotification: typeof import('./src/components/common/ToastNotification.vue')['default']
    VisiMisi: typeof import('./src/components/frontend/VisiMisi.vue')['default']
    WhatsAppFloatingButton: typeof import('./src/components/frontend/WhatsAppFloatingButton.vue')['default']
  }
}

// For TSX support
declare global {
  const AdminLayout: typeof import('./src/components/admin/layouts/AdminLayout.vue')['default']
  const BadgeButton: typeof import('./src/components/frontend/BadgeButton.vue')['default']
  const CardSkeleton: typeof import('./src/components/admin/common/CardSkeleton.vue')['default']
  const Footer: typeof import('./src/components/frontend/Footer.vue')['default']
  const FormSkeleton: typeof import('./src/components/admin/common/FormSkeleton.vue')['default']
  const GoogleMapEmbed: typeof import('./src/components/frontend/GoogleMapEmbed.vue')['default']
  const Header: typeof import('./src/components/frontend/Header.vue')['default']
  const Hero: typeof import('./src/components/frontend/Hero.vue')['default']
  const ImageGalleryModal: typeof import('./src/components/frontend/ImageGalleryModal.vue')['default']
  const ImagePlaceholder: typeof import('./src/components/common/ImagePlaceholder.vue')['default']
  const ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
  const Kontak: typeof import('./src/components/frontend/Kontak.vue')['default']
  const Navbar: typeof import('./src/components/admin/Navbar.vue')['default']
  const OurClient: typeof import('./src/components/frontend/OurClient.vue')['default']
  const Pagination: typeof import('./src/components/frontend/Pagination.vue')['default']
  const Produk: typeof import('./src/components/frontend/Produk.vue')['default']
  const Riwayat: typeof import('./src/components/frontend/Riwayat.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SectionTitle: typeof import('./src/components/frontend/SectionTitle.vue')['default']
  const Sidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
  const SkeletonLoader: typeof import('./src/components/admin/common/SkeletonLoader.vue')['default']
  const StatsSkeleton: typeof import('./src/components/admin/common/StatsSkeleton.vue')['default']
  const TableSkeleton: typeof import('./src/components/admin/common/TableSkeleton.vue')['default']
  const Testimoni: typeof import('./src/components/frontend/Testimoni.vue')['default']
  const ToastNotification: typeof import('./src/components/common/ToastNotification.vue')['default']
  const VisiMisi: typeof import('./src/components/frontend/VisiMisi.vue')['default']
  const WhatsAppFloatingButton: typeof import('./src/components/frontend/WhatsAppFloatingButton.vue')['default']
}