/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/admin/layouts/AdminLayout.vue')['default']
    BadgeButton: typeof import('./src/components/frontend/BadgeButton.vue')['default']
    Footer: typeof import('./src/components/frontend/Footer.vue')['default']
    Header: typeof import('./src/components/frontend/Header.vue')['default']
    Hero: typeof import('./src/components/frontend/Hero.vue')['default']
    'ILucide:arrowRight': typeof import('~icons/lucide/arrow-right')['default']
    'ILucide:arrowUp': typeof import('~icons/lucide/arrow-up')['default']
    'ILucide:arrowUpRight': typeof import('~icons/lucide/arrow-up-right')['default']
    'ILucide:box': typeof import('~icons/lucide/box')['default']
    'ILucide:building': typeof import('~icons/lucide/building')['default']
    'ILucide:calendar': typeof import('~icons/lucide/calendar')['default']
    'ILucide:chevronLeft': typeof import('~icons/lucide/chevron-left')['default']
    'ILucide:chevronRight': typeof import('~icons/lucide/chevron-right')['default']
    'ILucide:circle': typeof import('~icons/lucide/circle')['default']
    'ILucide:cube': typeof import('~icons/lucide/cube')['default']
    'ILucide:eye': typeof import('~icons/lucide/eye')['default']
    'ILucide:facebook': typeof import('~icons/lucide/facebook')['default']
    'ILucide:fileText': typeof import('~icons/lucide/file-text')['default']
    'ILucide:home': typeof import('~icons/lucide/home')['default']
    'ILucide:instagram': typeof import('~icons/lucide/instagram')['default']
    'ILucide:layout': typeof import('~icons/lucide/layout')['default']
    'ILucide:linkedin': typeof import('~icons/lucide/linkedin')['default']
    'ILucide:logOut': typeof import('~icons/lucide/log-out')['default']
    'ILucide:mail': typeof import('~icons/lucide/mail')['default']
    'ILucide:mapPin': typeof import('~icons/lucide/map-pin')['default']
    'ILucide:menu': typeof import('~icons/lucide/menu')['default']
    'ILucide:messageCircle': typeof import('~icons/lucide/message-circle')['default']
    'ILucide:package': typeof import('~icons/lucide/package')['default']
    'ILucide:phone': typeof import('~icons/lucide/phone')['default']
    'ILucide:ruler': typeof import('~icons/lucide/ruler')['default']
    'ILucide:scale': typeof import('~icons/lucide/scale')['default']
    'ILucide:settings': typeof import('~icons/lucide/settings')['default']
    'ILucide:shieldCheck': typeof import('~icons/lucide/shield-check')['default']
    'ILucide:star': typeof import('~icons/lucide/star')['default']
    'ILucide:twitter': typeof import('~icons/lucide/twitter')['default']
    'ILucide:user': typeof import('~icons/lucide/user')['default']
    'ILucide:userCog': typeof import('~icons/lucide/user-cog')['default']
    'ILucide:users': typeof import('~icons/lucide/users')['default']
    'ILucide:x': typeof import('~icons/lucide/x')['default']
    'ILucide:zap': typeof import('~icons/lucide/zap')['default']
    ImageGalleryModal: typeof import('./src/components/frontend/ImageGalleryModal.vue')['default']
    ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
    Kontak: typeof import('./src/components/frontend/Kontak.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/admin/Navbar.vue')['default']
    OurClient: typeof import('./src/components/frontend/OurClient.vue')['default']
    Pagination: typeof import('./src/components/frontend/Pagination.vue')['default']
    Produk: typeof import('./src/components/frontend/Produk.vue')['default']
    Riwayat: typeof import('./src/components/frontend/Riwayat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/frontend/SectionTitle.vue')['default']
    Sidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
    Testimoni: typeof import('./src/components/frontend/Testimoni.vue')['default']
    ToastNotification: typeof import('./src/components/common/ToastNotification.vue')['default']
    VisiMisi: typeof import('./src/components/frontend/VisiMisi.vue')['default']
    WhatsAppFloatingButton: typeof import('./src/components/frontend/WhatsAppFloatingButton.vue')['default']
  }
}

// For TSX support
declare global {
  const AdminLayout: typeof import('./src/components/admin/layouts/AdminLayout.vue')['default']
  const BadgeButton: typeof import('./src/components/frontend/BadgeButton.vue')['default']
  const Footer: typeof import('./src/components/frontend/Footer.vue')['default']
  const Header: typeof import('./src/components/frontend/Header.vue')['default']
  const Hero: typeof import('./src/components/frontend/Hero.vue')['default']
  const ImageGalleryModal: typeof import('./src/components/frontend/ImageGalleryModal.vue')['default']
  const ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
  const Kontak: typeof import('./src/components/frontend/Kontak.vue')['default']
  const Login: typeof import('./src/components/Login.vue')['default']
  const Navbar: typeof import('./src/components/admin/Navbar.vue')['default']
  const OurClient: typeof import('./src/components/frontend/OurClient.vue')['default']
  const Pagination: typeof import('./src/components/frontend/Pagination.vue')['default']
  const Produk: typeof import('./src/components/frontend/Produk.vue')['default']
  const Riwayat: typeof import('./src/components/frontend/Riwayat.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SectionTitle: typeof import('./src/components/frontend/SectionTitle.vue')['default']
  const Sidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
  const Testimoni: typeof import('./src/components/frontend/Testimoni.vue')['default']
  const ToastNotification: typeof import('./src/components/common/ToastNotification.vue')['default']
  const VisiMisi: typeof import('./src/components/frontend/VisiMisi.vue')['default']
  const WhatsAppFloatingButton: typeof import('./src/components/frontend/WhatsAppFloatingButton.vue')['default']
}